const KEY='focus-tracker-data-v4';
const OLD=['focus-tracker-data-v3','focus-tracker-data-v2','focus-tracker-data-v1'];
const DEFAULT_SETTINGS={moneyPrefixes:['AFF','SI','GT'],opsPrefixes:['CHECK','MEET','OPS']};
let state=loadState();ensureState();
function loadState(){let raw=localStorage.getItem(KEY);if(!raw){for(const k of OLD){raw=localStorage.getItem(k);if(raw)break}}if(!raw)return{sessions:[],active:null,reviews:{},settings:structuredClone(DEFAULT_SETTINGS)};try{return JSON.parse(raw)}catch{return{sessions:[],active:null,reviews:{},settings:structuredClone(DEFAULT_SETTINGS)}}}
function ensureState(){state.sessions=state.sessions||[];state.reviews=state.reviews||{};state.settings=state.settings||structuredClone(DEFAULT_SETTINGS);state.settings.moneyPrefixes=cleanPrefixes(state.settings.moneyPrefixes?.length?state.settings.moneyPrefixes:DEFAULT_SETTINGS.moneyPrefixes);state.settings.opsPrefixes=cleanPrefixes(state.settings.opsPrefixes?.length?state.settings.opsPrefixes:DEFAULT_SETTINGS.opsPrefixes)}
function save(){ensureState();localStorage.setItem(KEY,JSON.stringify(state))}
function cleanPrefixes(input){const arr=Array.isArray(input)?input:String(input||'').split(/[\n,]+/);return[...new Set(arr.map(x=>String(x).trim().toUpperCase()).filter(Boolean))]}
function pad(n){return String(n).padStart(2,'0')}function dateKey(d=new Date()){return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}function timeText(ts){const d=new Date(ts);return`${pad(d.getHours())}:${pad(d.getMinutes())}`}function minText(m){m=Math.max(0,Math.round(m));const h=Math.floor(m/60),r=m%60;return h&&r?`${h}h${r}p`:h?`${h}h`:`${r}p`}function mins(a,b){return Math.max(0,Math.round((b-a)/60000))}
function esc(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function prefix(name){const m=(name||'').trim().toUpperCase().match(/^([A-ZÀ-Ỵ0-9_]+)\b/);return m?m[1]:''}
function detectGroup(name){const p=prefix(name);if(!p)return'B';if(state.settings.moneyPrefixes.includes(p))return'A';if(state.settings.opsPrefixes.includes(p))return'C';return'B'}
function groupName(g){return g==='A'?'A - Tạo tiền':g==='B'?'B - Xây tài sản':'C - Vận hành'}function badge(g){return g==='A'?'badge-a':g==='B'?'badge-b':'badge-c'}function taskClass(g){return g==='A'?'task-a':g==='B'?'task-b':'task-c'}
function stat(s){const end=s.endTime||Date.now();const total=mins(s.startTime,end);const distract=(s.distractions||[]).reduce((a,d)=>a+Number(d.minutes||0),0);return{total,distract,work:Math.max(0,total-distract)}}
function aggregate(list){let total=0,distract=0,work=0;list.forEach(s=>{const x=stat(s);total+=x.total;distract+=x.distract;work+=x.work});return{total,distract,work,score:total?Math.round(work/total*100):0}}
function todaySessions(){return state.sessions.filter(s=>s.date===dateKey())}
function metrics(id,items){document.getElementById(id).innerHTML=items.map(i=>`<div class="metric-card"><p>${i.label}</p><strong>${i.value}</strong></div>`).join('')}
function allocation(list){const work={A:0,B:0,C:0};list.forEach(s=>work[s.group||detectGroup(s.name)]+=stat(s).work);const total=work.A+work.B+work.C;return{A:total?Math.round(work.A/total*100):0,B:total?Math.round(work.B/total*100):0,C:total?Math.round(work.C/total*100):0,work}}
function renderAllocation(id,list){const a=allocation(list);document.getElementById(id).innerHTML=`<div class="allocation-grid"><div class="allocation-card allocation-a"><span>Tạo tiền</span>${a.A}%</div><div class="allocation-card allocation-b"><span>Xây tài sản</span>${a.B}%</div><div class="allocation-card allocation-c"><span>Vận hành</span>${a.C}%</div></div>`}
function renderToday(){document.getElementById('todayDate').textContent=new Date().toLocaleDateString('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'});document.getElementById('prefixHelp').innerHTML=`<strong>Tự phân loại bằng tiền tố:</strong> ${state.settings.moneyPrefixes.join(' / ')} = Tạo tiền · ${state.settings.opsPrefixes.join(' / ')} = Vận hành. Không nhập hoặc không khớp thì mặc định Xây tài sản.`;const list=todaySessions();const all=list.concat(state.active?[state.active]:[]);const a=aggregate(all);metrics('todayMetrics',[{label:'Tổng giờ làm',value:minText(a.work)},{label:'Xao nhãng',value:minText(a.distract)},{label:'Focus score',value:`${a.score}%`},{label:'Block hoàn thành',value:list.length}]);renderAllocation('todayAllocation',all);renderActive();renderTable('todayTable',list,true);renderInsight();fillReview()}
function renderActive(){const el=document.getElementById('activeTaskCard');if(!state.active){el.classList.remove('active-task');el.innerHTML='<h2>Chưa có block đang chạy</h2><p class="hint">Nhập công việc và bấm <strong>Bắt đầu</strong>.</p>';return}el.classList.add('active-task');const x=stat(state.active),g=state.active.group;el.innerHTML=`<h2>Đang làm: <span class="task-label ${taskClass(g)}">${esc(state.active.name)}</span></h2><p class="hint">Bắt đầu lúc ${timeText(state.active.startTime)} · ${groupName(g)} · Năng lượng: ${state.active.energy}/5</p><div class="timer">${minText(x.total)}</div><p class="hint">Làm thật: <strong>${minText(x.work)}</strong> · Xao nhãng: <strong>${minText(x.distract)}</strong></p><div class="btn-row"><button class="btn btn-muted" onclick="quickBreak(5)">Nghỉ 5p</button><button class="btn btn-muted" onclick="quickBreak(15)">Nghỉ 15p</button><button class="btn btn-danger" onclick="openDistract()">Xao nhãng</button><button class="btn btn-success" onclick="endSession()">Kết thúc việc</button></div>`}
function renderTable(id,list,isToday){if(!list.length){document.getElementById(id).innerHTML=`<div class="empty">${isToday?'Hôm nay chưa có log nào.':'Chưa có dữ liệu log.'}</div>`;return}document.getElementById(id).innerHTML=`<table><thead><tr><th>Ngày</th><th>Bắt đầu</th><th>Kết thúc</th><th>Công việc</th><th>Nhóm</th><th>Làm thật</th><th>Xao nhãng</th><th>Nguyên nhân</th><th>Kết quả</th></tr></thead><tbody>${list.map(s=>{const x=stat(s),g=s.group||detectGroup(s.name);const reasons=(s.distractions||[]).map(d=>`${esc(d.reason)} (${d.minutes}p)`).join('<br>')||'-';return`<tr><td>${s.date}</td><td>${timeText(s.startTime)}</td><td>${s.endTime?timeText(s.endTime):'-'}</td><td><span class="task-label ${taskClass(g)}">${esc(s.name)}</span></td><td><span class="badge ${badge(g)}">${g}</span></td><td>${minText(x.work)}</td><td>${minText(x.distract)}</td><td>${reasons}</td><td>${esc(s.result||'')}</td></tr>`}).join('')}</tbody></table>`}
function countReasons(list){const r={};list.forEach(s=>(s.distractions||[]).forEach(d=>r[d.reason]=(r[d.reason]||0)+1));return r}
function renderInsight(){const all=todaySessions().concat(state.active?[state.active]:[]);const reasons=Object.entries(countReasons(all)).sort((a,b)=>b[1]-a[1])[0];document.getElementById('todayInsights').innerHTML=`<p><strong>Nguyên nhân xao nhãng chính:</strong> ${reasons?`${reasons[0]} (${reasons[1]} lần)`:'Chưa có dữ liệu'}.</p><p><strong>Gợi ý:</strong> Dùng nút nghỉ nhanh khi nghỉ chủ động để không lẫn với xao nhãng.</p>`}
function bar(id,data,suffix,divisor=1){const e=Object.entries(data).sort((a,b)=>b[1]-a[1]);if(!e.length){document.getElementById(id).innerHTML='<div class="empty">Chưa đủ dữ liệu.</div>';return}const max=Math.max(...e.map(x=>x[1]),1);document.getElementById(id).innerHTML=e.map(([label,value])=>`<div class="bar-item"><div class="bar-label"><span>${esc(label)}</span><span>${divisor===60?(value/60).toFixed(1).replace('.0',''):value} ${suffix}</span></div><div class="bar-bg"><div class="bar-fill" style="width:${Math.max(8,value/max*100)}%"></div></div></div>`).join('')}
function renderDashboard(){const a=aggregate(state.sessions);metrics('dashboardMetrics',[{label:'Tổng giờ làm',value:minText(a.work)},{label:'Tổng xao nhãng',value:minText(a.distract)},{label:'Focus score',value:`${a.score}%`},{label:'Tổng block',value:state.sessions.length}]);renderAllocation('dashboardAllocation',state.sessions);const groups={};state.sessions.forEach(s=>groups[groupName(s.group||detectGroup(s.name))]=(groups[groupName(s.group||detectGroup(s.name))]||0)+stat(s).work);bar('groupChart',groups,'giờ',60);bar('reasonChart',countReasons(state.sessions),'lần');document.getElementById('dashboardInsights').innerHTML='<p><strong>Insight:</strong> So sánh % phân bổ để biết ngày/tuần đang lệch sang tạo tiền, xây tài sản hay vận hành.</p>'}
function historySuggestions(){return[...new Set(state.sessions.map(s=>s.name).filter(Boolean))].slice(-80).reverse()}
function setupAutocomplete(){const input=document.getElementById('taskName');const datalist=document.getElementById('taskSuggestions');input.addEventListener('input',()=>{const q=input.value.toLowerCase();datalist.innerHTML=historySuggestions().filter(x=>x.toLowerCase().includes(q)).slice(0,10).map(x=>`<option value="${esc(x)}"></option>`).join('')})}
function startSession(e){e.preventDefault();if(state.active&&!confirm('Đang có một block chạy. Kết thúc block cũ và bắt đầu block mới?'))return;if(state.active)finishSession('Tự kết thúc khi bắt đầu block mới');const name=document.getElementById('taskName').value.trim();state.active={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:dateKey(),name,group:detectGroup(name),energy:document.getElementById('energy').value,startTime:Date.now(),endTime:null,result:'',distractions:[]};document.getElementById('startForm').reset();save();renderAll()}
function finishSession(def=''){const result=prompt('Kết quả block này là gì?',def||'');state.active.endTime=Date.now();state.active.result=result||'';state.sessions.push(state.active);state.active=null}
function endSession(){if(!state.active)return;finishSession();save();renderAll()}function quickBreak(m){if(!state.active)return;state.active.distractions.push({reason:`Break ${m}p`,minutes:m,note:'Nghỉ chủ động',time:Date.now()});save();renderAll()}function openDistract(){document.getElementById('distractModal').classList.add('open')}function closeDistract(){document.getElementById('distractModal').classList.remove('open');document.getElementById('distractForm').reset()}function saveDistraction(e){e.preventDefault();if(!state.active)return;state.active.distractions.push({reason:document.getElementById('distractReason').value,minutes:Number(document.getElementById('distractMinutes').value||0),note:document.getElementById('distractNote').value.trim(),time:Date.now()});save();closeDistract();renderAll()}
function fillReview(){const r=state.reviews[dateKey()]||{};bestWork.value=r.bestWork||'';wasteTime.value=r.wasteTime||'';satisfaction.value=r.satisfaction||'8'}function saveReview(e){e.preventDefault();state.reviews[dateKey()]={bestWork:bestWork.value.trim(),wasteTime:wasteTime.value.trim(),satisfaction:satisfaction.value};save();alert('Đã lưu review hôm nay.')}
function fillSettings(){moneyPrefixes.value=state.settings.moneyPrefixes.join('\n');opsPrefixes.value=state.settings.opsPrefixes.join('\n')}function savePrefixes(e){e.preventDefault();state.settings.moneyPrefixes=cleanPrefixes(moneyPrefixes.value);state.settings.opsPrefixes=cleanPrefixes(opsPrefixes.value);state.sessions.forEach(s=>s.group=detectGroup(s.name));if(state.active)state.active.group=detectGroup(state.active.name);save();renderAll();fillSettings();alert('Đã lưu quy tắc phân loại.')}function resetPrefixes(){state.settings=structuredClone(DEFAULT_SETTINGS);savePrefixes(new Event('submit'))}
function switchPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='log')renderTable('allLogTable',[...state.sessions].reverse(),false);if(page==='dashboard')renderDashboard();if(page==='settings')fillSettings();if(page==='today')renderToday()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`focus-tracker-${dateKey()}.json`;a.click();URL.revokeObjectURL(url)}function clearData(){if(!confirm('Xóa toàn bộ dữ liệu trên trình duyệt này?'))return;[KEY,...OLD].forEach(k=>localStorage.removeItem(k));state={sessions:[],active:null,reviews:{},settings:structuredClone(DEFAULT_SETTINGS)};save();renderAll();fillSettings()}
function renderAll(){renderToday();renderTable('allLogTable',[...state.sessions].reverse(),false);renderDashboard()}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>switchPage(btn.dataset.page)));startForm.addEventListener('submit',startSession);distractForm.addEventListener('submit',saveDistraction);closeModalBtn.addEventListener('click',closeDistract);reviewForm.addEventListener('submit',saveReview);prefixForm.addEventListener('submit',savePrefixes);resetPrefixBtn.addEventListener('click',resetPrefixes);exportBtn.addEventListener('click',exportData);clearBtn.addEventListener('click',clearData);setupAutocomplete();renderAll();fillSettings();setInterval(()=>{if(state.active)renderToday()},10000)});